# Generated by Django 6.0.1 on 2026-03-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
        ('specialities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='speciality_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='specialities.specialityyear'),
        ),
    ]
