# Generated by Django 6.0.1 on 2026-04-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='matricule',
        ),
    ]
