# Generated by Django 6.0.1 on 2026-03-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialityYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(choices=[('DSIA', 'Data Science'), ('MI', 'Management Industriel')], max_length=10)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialitySemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(default=1)),
                ('speciality_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='specialities.specialityyear')),
            ],
            options={
                'unique_together': {('speciality_year', 'semester')},
            },
        ),
    ]
